"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar'
import {ThemeProvider} from 'next-themes'
import Footer from './components/Footer'

// ssh-rsa-dTgqC3rJ1
// export const meta = {
//   title: 'Sanskar Pareta',
//   description: 'Generated by create next app',
// }


export default function RootLayout({ children }) {
  
  return (
    
    <html lang="en" >
      <body className= "dark:bg-stone-950"
        >
        <ThemeProvider enableSystem = {true} attribute="class">
          <Navbar/>
          {children}
          <Footer/>
        </ThemeProvider>  
       
      </body>
    </html>
  )
}
 